displayName=Braindead Farming
author=alex-1121
description=No more need to plan your farming and birdhouse runs. Turn off your brain and just follow the instructions.
tags=farming,farm,runs,osrs
plugins=com.braindeadfarming.BraindeadFarmingPlugin
